(define (same-parity-list first succ)
  (if (null? succ)
   (list first)   
   (if (= (remainder first 2) (remainder (car succ) 2))
       (cons first (same-parity-list (car succ) (cdr succ)))
       (same-parity-list first (cdr succ))
       )
      )
  )

(define (same-parity first . succ)
 (same-parity-list first succ) 
  )
(same-parity  1 2 3 4 5 7 9 10 11 101)
(same-parity  2 4)
(same-parity  2 )
